### ISSUE TITLE
Add the data in `ScheduleData.js`

### ISSUE THREAD

**Issue by inclinedadarsh** [Bachelors-in-Open-Source/ghw-schedule#2]
Add all the data for the January Schedule of MLH GHW in the `src/data/ScheduleData.js` file

You can get the data from the [official schedule](https://ghw.mlh.io/schedule) and then convert it in IST before using it.

**Comment by Anuragwagh** [comment]
I will add  all the data for the January Schedule of MLH GHW in IST, Assign me

**Comment by inclinedadarsh** [comment]
Definitely go for it!
Also, please make sure you do it before 9th because MLH GHW Jan begins on 9th Jan.

Thanks @Anuragwagh

**Comment by inclinedadarsh** [comment]
Thanks @Anuragwagh
