### ISSUE TITLE
Design Favicon for the website

### ISSUE THREAD

**Issue by inclinedadarsh** [Bachelors-in-Open-Source/ghw-schedule#3]
Design a favicon for the website. Make sure it's not NSFW and make sure it uses the color theme of the website.

**Comment by ASproson** [comment]
PR for review: https://github.com/Bachelors-in-Open-Source/ghw-schedule/pull/5

**Comment by inclinedadarsh** [comment]
Thanks @ASproson

**Comment by inclinedadarsh** [comment]
Thanks @ASproson
